my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: dbt_user
      password: dbt_password
      port: 5432
      dbname: analytics
      schema: public
      threads: 1