my_project:
  outputs:
    dev:
      dbname: analytics
      host: postgres
      pass: dbt_password
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: dbt_user
  target: dev
